### ISSUE TITLE
Relaying a message with a different sourceSystemID

### ISSUE THREAD

**Issue by sanderux** [aler9/gomavlib#32]
I am trying to change the contents of a message before relaying it, however, i need to also change the sourceSystemId and sourceComponentID. 

I need to set it to the original values from the frame.
Any help is highly appreciated.

`	for evt := range node.Events() {
		if frm, ok := evt.(*gomavlib.EventFrame); ok {

			if frm.Message().GetID() == 269 {
				msg := frm.Message().(*common.MessageVideoStreamInformation)

				msg.Uri = strings.Replace(msg.Uri, "127.0.0.1", "10.2.2.112", 1)
				fmt.Printf("received: id=%d, %+v\n", frm.Message().GetID(), msg)
				node.WriteMessageExcept(frm.Channel, msg)`

**Comment by aler9** [comment]
This has been fixed by adding `node.FixFrame()` and the `route-edit` example:

https://github.com/aler9/gomavlib/blob/main/examples/router-edit/main.go
